# Generated by Django 3.2.2 on 2021-05-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bronie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=45)),
                ('Rodzaj', models.CharField(max_length=20)),
                ('Typ_amunicji', models.CharField(max_length=20)),
                ('Cena_broni', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronie', models.CharField(max_length=45)),
                ('amunicja', models.CharField(max_length=45)),
                ('popularne', models.CharField(max_length=45)),
            ],
        ),
    ]
