# Generated by Django 3.2.2 on 2021-05-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bronie',
            options={'verbose_name_plural': 'Bronie'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name_plural': 'Kategoria'},
        ),
    ]
