# Generated by Django 3.2.2 on 2021-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20210524_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amunicja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=20)),
                ('Typ_amunicji', models.CharField(max_length=20)),
                ('Cena_amunicji', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Amunicja',
            },
        ),
    ]
