# Generated by Django 3.2.2 on 2021-05-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_auto_20210530_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronie',
            name='Nazwa',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
