# Generated by Django 3.2.2 on 2021-06-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20210601_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktualizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=60)),
                ('Opis', models.CharField(max_length=1000)),
                ('Data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
